config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'

  get 'messages/create'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :pictures do
    collection do
      post :confirm
    end
  end

  resources :topics do
    resources :comments
    collection do
      post :confirm
    end
  end
  
  resources :conversations do
    resources :messages
  end

  devise_for :users , controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  resources :users, only: [:index]

  resources :relationships, only: [:create, :destroy]

  root 'top#index'

  get 'things/index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def edit
    @comment = Comment.find(params[:id])
    @topic = @comment.topic
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    
    redirect_to topic_path(@comment.topic), notice: "ブログを編集しました！"
  end

  def create
    # Topicをパラメータの値から探し出し,Topicに紐づくcommentsとしてbuildします。
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: 'コメントを投稿しました。' }
        format.js {render :index}
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js {render :index }
    end
  end

  private
    # ストロングパラメーター
    def comment_params
      params.require(:comment).permit(:topic_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="container">
  <%= form_for([topic,comment], remote: true) do |f| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= comment.errors.count %>件のエラーがあります。</h2>
        <% comment.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </div>
    <% end %>
    <%= f.hidden_field :topic_id %>
    <div class="row control-group">
      <div class="form-group col-xs-12 floating-label-form-group controls">
        <%= f.label :content %>
        <%= f.text_field :content, autocomplete: "off", class: "form-control", placeholder: "コメント", required: true %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-xs-12">
        <%= f.submit "投稿" , class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_index.html.erb
<div class="container">
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
        <p class="left"><%= comment.user.name.present? ? comment.user.name : comment.user.email %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
    <% end %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<header class="intro-header" style="background-image:url(<%= asset_path "topic-bg.jpg" %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1>コメントの編集</h1>
          <hr class="small">
        </div>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <%= form_for(@comment, url: topic_comment_path) do |f| %>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= @comment.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <div class="field">
        <%= f.text_field :content, class:'form-control', placeholder: "コメント" , required: true%>
      </div>
      <div class="row">
        <div class="form-group col-xs-12">
          <%= f.submit '更新', class:'btn btn-default' %>
        </div>
      </div>
  <% end %>
  <%= link_to '戻る', topic_path(@topic) %>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')