config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'

  get 'messages/create'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :pictures do
    collection do
      post :confirm
    end
  end

  resources :topics do
    resources :comments
    collection do
      post :confirm
    end
  end
  
  resources :conversations do
    resources :messages
  end

  devise_for :users , controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  resources :users, only: [:index]

  resources :relationships, only: [:create, :destroy]

  root 'top#index'

  get 'things/index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
    mount_uploader :picture, PictureUploader

    validates :title, presence: true
    validates :picture, presence: true

    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only:[:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @topics = Topic.all
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end

  def new
    if params[:back]
      @topic = Topic.new(topics_params)
    else
      @topic = Topic.new
    end
  end

  def edit
  end
  
  def update
    @topic.update(topics_params)
    
    redirect_to topics_path, notice: "投稿を編集しました！"
  end

  def confirm
    @topic = Topic.new(topics_params)
    render :new if @topic.invalid?
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topics_path, notice: "写真を投稿しました！"
    else
      render 'new'
    end
  end

  def destroy
    @topic.destroy
    
    redirect_to topics_path, notice: "投稿を削除しました！"
  end

  private
    def topics_params
      params.require(:topic).permit(:title, :text, :picture, :picture_cache)
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_topics_path
    elsif action_name == 'edit'
      topic_path
    end
  end
end

app/views/topics/_form.html.erb
<%= form_for(@topic, url: choose_new_or_edit, html: {multipart: true}) do |f| %>
<% if @topic.errors.any? %>
  <div id="error_explanation">
    <h2><%= @topic.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  </div>
<% end %>

<div class="field">
  <%= f.text_field :title, class:'form-control', placeholder: "タイトル" %>
</div>

<div class="field">
  <%= f.text_field :text, class:'form-control', placeholder: "内容" %>
</div>

<div class="field">
  <%= image_tag @topic.picture if @topic.picture? %>
  <%= f.file_field :picture, class: "btn btn-default" %>
  <%= f.hidden_field :picture_cache %>
</div>

<hr>

<div class="actions">
  <%= f.submit '投稿', class:'btn btn-default' %>
</div>
<% end %>

<%= link_to "投稿一覧画面にもどる", topics_path %>

app/views/topics/confirm.html.erb
<header class="intro-header" style="background-image:url(<%= asset_path "login-bg.jpg" %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1>確認</h1>
          <hr class="small">
          <span class="subheading"></span>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@topic) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :text %>
      <%= f.hidden_field :picture %>
      <%= f.hidden_field :picture_cache %>
      <p>タイトル:<%= @topic.title %></p>
      <p>本文:<%= @topic.text %></p>
      <%= image_tag(@topic.picture, alt: @topic.title, class: "trim-image-to-circle") %>
      <%= f.submit "登録",class: 'btn btn-primary btn-block' %>
    <% end %>
    <%= form_for(@topic, url: new_topic_path, method: 'get', html: {multipart: true}) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :text %>
      <%= f.hidden_field :picture %>
      <%= f.hidden_field :picture_cache %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<header class="intro-header" style="background-image:url(<%= asset_path "login-bg.jpg" %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1>編集</h1>
          <hr class="small">
          <span class="subheading">下記から変更できます。</span>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <%= render 'form' %>
  </div>
</div>

app/views/topics/index.html.erb
<header class="intro-header" style="background-image:url(<%= asset_path "topic-bg.jpg" %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1>みんなのおきにいり</h1>
          <hr class="small">
          <span class="subheading"></span>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <%= link_to "投稿する", new_topic_path, class: 'btn btn-default' %>
      <hr>
      <% @topics.each do |topic| %>
        <div class="post-preview">
          <%= link_to topic_path(topic) do %>
            <h2 class="post-title">
              <%= topic.title %>
            </h2>
            <h3 class="post-subtitle">
            </h3>
          <% end %>
          <p class="post-meta">投稿者 <%= topic.user.name.present? ? topic.user.name : topic.user.email + " (名前を登録していないとメールアドレスを表示します。) " %> , <%= topic.created_at.to_s %> </p>
        </div>
        <% if current_user.id == topic.user.id %>
          <%= link_to "編集", edit_topic_path(topic.id), class: 'btn btn-default btn-sm btn-success' %>
          <%= link_to "削除", topic_path(topic.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
        <% end %>
        <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<header class="intro-header" style="background-image:url(<%= asset_path "login-bg.jpg" %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1>新規投稿</h1>
          <hr class="small">
          <span class="subheading"></span>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ものの写真を投稿する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/topics/show.html.erb
<header class="intro-header" style="background-image:url(<%= asset_path "topic-bg.jpg" %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1>詳細</h1>
          <hr class="small">
          <span class="subheading"><%= @topic.title %></span>
          <span class="meta">投稿日 <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %></span>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <a href="<%= @topic.picture %>" class="thumbnail">
        <%= image_tag(@topic.picture, alt: @topic.title )%>
      </a>
      <p><%= @topic.text %></p>
      <hr>
    </div>
  </div>
</div>

<div class="row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <div class="container">
      <%= link_to '戻る', topics_path %>
    </div>
  </div>
</div>