config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'

  get 'messages/create'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :pictures do
    collection do
      post :confirm
    end
  end

  resources :topics do
    resources :comments
    collection do
      post :confirm
    end
  end
  
  resources :conversations do
    resources :messages
  end

  devise_for :users , controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  resources :users, only: [:index]

  resources :relationships, only: [:create, :destroy]

  root 'top#index'

  get 'things/index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
    mount_uploader :picture, PictureUploader

    validates :title, presence: true
    validates :picture, presence: true

    belongs_to :user
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only:[:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(pictures_params)
    else
      @picture = Picture.new
    end
  end

  def edit
  end
  
  def update
    @picture.update(pictures_params)
    
    redirect_to pictures_path, notice: "投稿を編集しました！"
  end

  def confirm
    @picture = Picture.new(pictures_params)
    render :new if @picture.invalid?
  end

  def create
    @picture = Picture.new(pictures_params)
    @picture.user_id = current_user.id
    if @picture.save
      redirect_to pictures_path, notice: "写真を投稿しました！"
      #NoticeMailer.sendmail_picture(@picture).deliver
    else
      render 'new'
    end
  end

  def destroy
    @picture.destroy
    
    redirect_to pictures_path, notice: "投稿を削除しました！"
  end

  private
    def pictures_params
      params.require(:picture).permit(:title, :content, :picture, :picture_cache)
    end

    def set_picture
      @picture = Picture.find(params[:id])
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
      def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/views/pictures/_form.html.erb
<%= form_for(@picture, url: choose_new_or_edit, html: {multipart: true}) do |f| %>
<% if @picture.errors.any? %>
  <div id="error_explanation">
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  </div>
<% end %>

<div class="field">
  <%= f.text_field :title, class:'form-control', placeholder: "タイトル" %>
</div>

<div class="field">
  <%= f.text_field :content, class:'form-control', placeholder: "内容" %>
</div>

<div class="field">
  <%= image_tag @picture.picture if @picture.picture? %>
  <%= f.file_field :picture %>
  <%= f.hidden_field :picture_cache %>
</div>

<div class="actions">
  <%= f.submit '投稿', class:'btn btn-primary btn-block' %>
</div>
<% end %>

<%= link_to "投稿一覧画面にもどる", pictures_path %>

app/views/pictures/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@picture) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.hidden_field :picture %>
      <%= f.hidden_field :picture_cache %>
      <p>タイトル:<%= @picture.title %></p>
      <p>本文:<%= @picture.content %></p>
      <%= image_tag(@picture.picture, alt: @picture.title, class: "trim-image-to-circle") %>
      <%= f.submit "登録",class: 'btn btn-primary btn-block' %>
    <% end %>
    <%= form_for(@picture, url: new_picture_path, method: 'get', html: {multipart: true}) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.hidden_field :picture %>
      <%= f.hidden_field :picture_cache %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h1>写真一覧</h1>
      <%= link_to "投稿する", new_picture_path, class: 'btn btn-default' %>
      <hr/>
    <% @pictures.each do |picture| %>
      <div class="panel panel-success">
        <div class="panel-heading">
          <h2 class="panel-title"><strong>タイトル：<%= picture.title %></strong></h2>
          <h4 class="panel-title"><small>投稿日：<%= picture.created_at.to_s %></small></h4>
        </div>
        <div class="panel-body">
          <p><%= picture.content %></p>
          <%= image_tag(picture.picture, alt: picture.title )%>
        </div>
        <div class="panel-footer">
          <h4 class="panel-title">投稿者：<%= picture.user.name.present? ? picture.user.name : picture.user.email + " (名前を登録していないとメールアドレスを表示します。) " %></h4>        
        </div>
      </div>
      <%= link_to "編集", edit_picture_path(picture.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
      <hr/>
    <% end %>
  </div>
</div>